@startuml @endregex
entity "user" as U{
  * id 
  ---
  * Role 
  * nom 
  * prénom
  * adresse
  * téléphone
}

entity "Article" as A{
  * id
  ---
  * prix
  * description
  * Titre 
  * disponibilite
}

' join table article-order
entity "panier" as P{
  *id
  ---
}

entity "Panier_Articles" as PA {
  * id
  ---
  * panier_id
  * article_id
  * quantité
}

entity "Order" as O{
  * id
  ---
  * user_id
  * panier_id
  * database* montant
}

U  ||--o{ O 
A }o--o{ P
O ||--|| P

@enduml